# Generated by Django 4.0.5 on 2024-09-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='due_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='facturassub',
            name='pagado',
            field=models.DecimalField(decimal_places=0, max_digits=65),
        ),
    ]
