# Generated by Django 4.0.5 on 2024-09-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_facturas_due_at_alter_facturassub_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='due_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
