# Generated by Django 4.0.5 on 2024-09-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_alter_facturas_due_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='due_at',
            field=models.DateTimeField(),
        ),
    ]
