# Generated by Django 4.0.5 on 2024-09-21 09:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0004_alter_facturas_due_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogsTypesGastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogsTypesOtrosIngresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gastos',
            name='codigo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gastos',
            name='descripcion',
            field=models.CharField(default='nada', max_length=255),
        ),
        migrations.AddField(
            model_name='gastos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='gastos',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facturassub',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='facturassub',
            name='pagado',
            field=models.DecimalField(decimal_places=0, max_digits=25),
        ),
        migrations.CreateModel(
            name='OtroIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=200, null=True)),
                ('consecutivo', models.PositiveIntegerField(unique=True)),
                ('descripcion', models.CharField(default='nada', max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.catalogstypesotrosingresos')),
            ],
        ),
        migrations.AddField(
            model_name='gastos',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Finance.catalogstypesgastos'),
            preserve_default=False,
        ),
    ]
