# Generated by Django 4.0.5 on 2024-10-14 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0005_catalogstypesgastos_catalogstypesotrosingresos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturassub',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='otroingreso',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
