# Generated by Django 4.0.5 on 2024-12-24 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Finance', '0009_gastos_propietario_otroingreso_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='propietario',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='otroingreso',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
