# Generated by Django 4.2.8 on 2023-12-09 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_delete_catalogstypesgen_user_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='document',
            new_name='documento',
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 3, 5, 51, 15219)),
        ),
    ]
