# Generated by Django 4.2.8 on 2023-12-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_catalogstypesactivities_alter_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogsJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada', models.CharField(default='Mañana', max_length=200)),
            ],
        ),
    ]
