# Generated by Django 4.2.8 on 2023-12-30 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_catalogsjornada_jornada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogstypesactivities',
            name='observaciones',
        ),
    ]
