# Generated by Django 4.0.5 on 2024-12-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_remove_catalogstypesactivities_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cambiar_contrasena',
            field=models.BooleanField(default=True),
        ),
    ]
