# Generated by Django 4.2.8 on 2023-12-13 01:40

import applications.User.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0005_catalogstypesactivities_alter_user_created_at'),
        ('Programs', '0002_alter_periodos_an_creacion_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('cedula', models.CharField(max_length=20, validators=[applications.User.validators.validate_cero], verbose_name='Identificación del Estudiante')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('nacionalidad', models.CharField(choices=[('Afghanistan', 'Afghanistan'), ('Albania', 'Albania'), ('Algeria', 'Algeria'), ('American\xa0Samoa', 'American\xa0Samoa'), ('Andorra', 'Andorra'), ('Angola', 'Angola'), ('Anguilla', 'Anguilla'), ('Antarctica', 'Antarctica'), ('Antigua\xa0&\xa0Barbuda', 'Antigua\xa0&\xa0Barbuda'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('Aruba', 'Aruba'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Azerbaijan', 'Azerbaijan'), ('Bahama', 'Bahama'), ('Bahrain', 'Bahrain'), ('Bangladesh', 'Bangladesh'), ('Barbados', 'Barbados'), ('Belarus', 'Belarus'), ('Belgium', 'Belgium'), ('Belize', 'Belize'), ('Benin', 'Benin'), ('Bermuda', 'Bermuda'), ('Bhutan', 'Bhutan'), ('Bolivia', 'Bolivia'), ('Bosnia\xa0and\xa0Herzegovina', 'Bosnia\xa0and\xa0Herzegovina'), ('Botswana', 'Botswana'), ('Bouvet\xa0Island', 'Bouvet\xa0Island'), ('Brazil', 'Brazil'), ('British\xa0Indian\xa0Ocean\xa0Territory', 'British\xa0Indian\xa0Ocean\xa0Territory'), ('British\xa0Virgin\xa0Islands', 'British\xa0Virgin\xa0Islands'), ('Brunei\xa0Darussalam', 'Brunei\xa0Darussalam'), ('Bulgaria', 'Bulgaria'), ('Burkina\xa0Faso', 'Burkina\xa0Faso'), ('Burundi', 'Burundi'), ('Cambodia', 'Cambodia'), ('Cameroon', 'Cameroon'), ('Canada', 'Canada'), ('Cape\xa0Verde', 'Cape\xa0Verde'), ('Cayman\xa0Islands', 'Cayman\xa0Islands'), ('Central\xa0African\xa0Republic', 'Central\xa0African\xa0Republic'), ('Chad', 'Chad'), ('Chile', 'Chile'), ('China', 'China'), ('Christmas\xa0Island', 'Christmas\xa0Island'), ('Cocos\xa0\xa0Keeling\xa0Islands', 'Cocos\xa0\xa0Keeling\xa0Islands'), ('Colombia', 'Colombia'), ('Comoros', 'Comoros'), ('Congo', 'Congo'), ('Cook\xa0Iislands', 'Cook\xa0Iislands'), ('Costa\xa0Rica', 'Costa\xa0Rica'), ('Croatia', 'Croatia'), ('Cuba', 'Cuba'), ('Cyprus', 'Cyprus'), ('Czech\xa0Republic', 'Czech\xa0Republic'), ('Denmark', 'Denmark'), ('Djibouti', 'Djibouti'), ('Dominica', 'Dominica'), ('Dominican\xa0Republic', 'Dominican\xa0Republic'), ('East\xa0Timor', 'East\xa0Timor'), ('Ecuador', 'Ecuador'), ('Egypt', 'Egypt'), ('El\xa0Salvador', 'El\xa0Salvador'), ('Equatorial\xa0Guinea', 'Equatorial\xa0Guinea'), ('Eritrea', 'Eritrea'), ('Estonia', 'Estonia'), ('Ethiopia', 'Ethiopia'), ('Falkland\xa0Islands\xa0\xa0Malvinas', 'Falkland\xa0Islands\xa0\xa0Malvinas'), ('Faroe\xa0Islands', 'Faroe\xa0Islands'), ('Fiji', 'Fiji'), ('Finland', 'Finland'), ('France', 'France'), ('France', 'France'), ('French\xa0Guiana', 'French\xa0Guiana'), ('French\xa0Polynesia', 'French\xa0Polynesia'), ('French\xa0Southern\xa0Territories', 'French\xa0Southern\xa0Territories'), ('Gabon', 'Gabon'), ('Gambia', 'Gambia'), ('Georgia', 'Georgia'), ('Germany', 'Germany'), ('Ghana', 'Ghana'), ('Gibraltar', 'Gibraltar'), ('Greece', 'Greece'), ('Greenland', 'Greenland'), ('Grenada', 'Grenada'), ('Guadeloupe', 'Guadeloupe'), ('Guam', 'Guam'), ('Guatemala', 'Guatemala'), ('Guinea', 'Guinea'), ('Guinea-Bissau', 'Guinea-Bissau'), ('Guyana', 'Guyana'), ('Haiti', 'Haiti'), ('Heard\xa0&\xa0McDonald\xa0Islands', 'Heard\xa0&\xa0McDonald\xa0Islands'), ('Honduras', 'Honduras'), ('Hong\xa0Kong', 'Hong\xa0Kong'), ('Hungary', 'Hungary'), ('Iceland', 'Iceland'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Iraq', 'Iraq'), ('Ireland', 'Ireland'), ('Islamic\xa0Republic\xa0of\xa0Iran', 'Islamic\xa0Republic\xa0of\xa0Iran'), ('Israel', 'Israel'), ('Italy', 'Italy'), ('Ivory\xa0Coast', 'Ivory\xa0Coast'), ('Jamaica', 'Jamaica'), ('Japan', 'Japan'), ('Jordan', 'Jordan'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Kiribati', 'Kiribati'), ('Korea', 'Korea'), ('Kuwait', 'Kuwait'), ('Kyrgyzstan', 'Kyrgyzstan'), ('Lao\xa0People\xa0Democratic\xa0Republic', 'Lao\xa0People\xa0Democratic\xa0Republic'), ('Latvia', 'Latvia'), ('Lebanon', 'Lebanon'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'), ('Libyan\xa0Arab\xa0Jamahiriya', 'Libyan\xa0Arab\xa0Jamahiriya'), ('Liechtenstein', 'Liechtenstein'), ('Lithuania', 'Lithuania'), ('Luxembourg', 'Luxembourg'), ('Macau', 'Macau'), ('Madagascar', 'Madagascar'), ('Malawi', 'Malawi'), ('Malaysia', 'Malaysia'), ('Maldives', 'Maldives'), ('Mali', 'Mali'), ('Malta', 'Malta'), ('Marshall\xa0Islands', 'Marshall\xa0Islands'), ('Martinique', 'Martinique'), ('Mauritania', 'Mauritania'), ('Mauritius', 'Mauritius'), ('Mayotte', 'Mayotte'), ('Mexico', 'Mexico'), ('Micronesia', 'Micronesia'), ('Moldova', 'Moldova'), ('Monaco', 'Monaco'), ('Mongolia', 'Mongolia'), ('Monserrat', 'Monserrat'), ('Morocco', 'Morocco'), ('Mozambique', 'Mozambique'), ('Myanmar', 'Myanmar'), ('Namibia', 'Namibia'), ('Nauru', 'Nauru'), ('Nepal', 'Nepal'), ('Netherlands', 'Netherlands'), ('Netherlands\xa0Antilles', 'Netherlands\xa0Antilles'), ('New\xa0Caledonia', 'New\xa0Caledonia'), ('New\xa0Zealand', 'New\xa0Zealand'), ('Nicaragua', 'Nicaragua'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('Niue', 'Niue'), ('Norfolk\xa0Island', 'Norfolk\xa0Island'), ('Northern\xa0Mariana\xa0Islands', 'Northern\xa0Mariana\xa0Islands'), ('Norway', 'Norway'), ('Oman', 'Oman'), ('Pakistan', 'Pakistan'), ('Palau', 'Palau'), ('Panama', 'Panama'), ('Papua\xa0New\xa0Guinea', 'Papua\xa0New\xa0Guinea'), ('Paraguay', 'Paraguay'), ('Peru', 'Peru'), ('Philippines', 'Philippines'), ('Pitcairn', 'Pitcairn'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Puerto\xa0Rico', 'Puerto\xa0Rico'), ('Qatar', 'Qatar'), ('Reunion', 'Reunion'), ('Romania', 'Romania'), ('Russian\xa0Federation', 'Russian\xa0Federation'), ('Rwanda', 'Rwanda'), ('Saint\xa0Lucia', 'Saint\xa0Lucia'), ('Samoa', 'Samoa'), ('San\xa0Marino', 'San\xa0Marino'), ('Sao\xa0Tome\xa0&\xa0Principe', 'Sao\xa0Tome\xa0&\xa0Principe'), ('Saudi\xa0Arabia', 'Saudi\xa0Arabia'), ('Senegal', 'Senegal'), ('Seychelles', 'Seychelles'), ('Sierra\xa0Leone', 'Sierra\xa0Leone'), ('Singapore', 'Singapore'), ('Slovakia', 'Slovakia'), ('Slovenia', 'Slovenia'), ('Solomon\xa0Islands', 'Solomon\xa0Islands'), ('Somalia', 'Somalia'), ('South\xa0Africa', 'South\xa0Africa'), ('South\xa0Georgia\xa0and\xa0the\xa0South\xa0Sandwich\xa0Islands', 'South\xa0Georgia\xa0and\xa0the\xa0South\xa0Sandwich\xa0Islands'), ('Spain', 'Spain'), ('Sri\xa0Lanka', 'Sri\xa0Lanka'), ('St.\xa0Helena', 'St.\xa0Helena'), ('St.\xa0Kitts\xa0and\xa0Nevis', 'St.\xa0Kitts\xa0and\xa0Nevis'), ('St.\xa0Pierre\xa0&\xa0Miquelon', 'St.\xa0Pierre\xa0&\xa0Miquelon'), ('St.\xa0Vincent\xa0&\xa0the\xa0Grenadines', 'St.\xa0Vincent\xa0&\xa0the\xa0Grenadines'), ('Sudan', 'Sudan'), ('Suriname', 'Suriname'), ('Svalbard\xa0&\xa0Jan\xa0Mayen\xa0Islands', 'Svalbard\xa0&\xa0Jan\xa0Mayen\xa0Islands'), ('Swaziland', 'Swaziland'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Syrian\xa0Arab\xa0Republic', 'Syrian\xa0Arab\xa0Republic'), ('Taiwan', 'Taiwan'), ('Tajikistan', 'Tajikistan'), ('Tanzania', 'Tanzania'), ('Thailand', 'Thailand'), ('Togo', 'Togo'), ('Tokelau', 'Tokelau'), ('Tonga', 'Tonga'), ('Trinidad\xa0&\xa0Tobago', 'Trinidad\xa0&\xa0Tobago'), ('Tunisia', 'Tunisia'), ('Turkey', 'Turkey'), ('Turkmenistan', 'Turkmenistan'), ('Turks\xa0&\xa0Caicos\xa0Islands', 'Turks\xa0&\xa0Caicos\xa0Islands'), ('Tuvalu', 'Tuvalu'), ('Uganda', 'Uganda'), ('Ukraine', 'Ukraine'), ('United\xa0Arab\xa0Emirates', 'United\xa0Arab\xa0Emirates'), ('United\xa0Kingdom\xa0\xa0Great\xa0Britain', 'United\xa0Kingdom\xa0\xa0Great\xa0Britain'), ('United\xa0States\xa0Minor\xa0Outlying\xa0Islands', 'United\xa0States\xa0Minor\xa0Outlying\xa0Islands'), ('United\xa0States\xa0Virgin\xa0Islands', 'United\xa0States\xa0Virgin\xa0Islands'), ('United\xa0States\xa0of\xa0America', 'United\xa0States\xa0of\xa0America'), ('Uruguay', 'Uruguay'), ('Uzbekistan', 'Uzbekistan'), ('Vanuatu', 'Vanuatu'), ('Vatican\xa0City\xa0State\xa0\xa0Holy\xa0See', 'Vatican\xa0City\xa0State\xa0\xa0Holy\xa0See'), ('Venezuela', 'Venezuela'), ('Viet\xa0Nam', 'Viet\xa0Nam'), ('Wallis\xa0&\xa0Futuna\xa0Islands', 'Wallis\xa0&\xa0Futuna\xa0Islands'), ('Western\xa0Sahara', 'Western\xa0Sahara'), ('Yemen', 'Yemen'), ('Yugoslavia', 'Yugoslavia'), ('Zaire', 'Zaire'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')], default='Colombia', max_length=100, verbose_name='Nacionalidad')),
                ('telefono', models.CharField(max_length=10, validators=[applications.User.validators.validate_telefono], verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('nacimiento', models.DateField(validators=[applications.User.validators.clean_nacimiento2], verbose_name='Fecha de Nacimiento')),
                ('costo_cierre', models.DecimalField(decimal_places=0, default=0, max_digits=25)),
                ('email', models.EmailField(max_length=254, verbose_name='Em@il')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otros', 'Otros')], default='Femenino', max_length=50, verbose_name='sexo')),
                ('fecha_reg', models.DateField(default=datetime.datetime.now, verbose_name='Fecha')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Usuario')),
                ('nombre_acudiente', models.CharField(max_length=100, verbose_name='Nombres del acudiente')),
                ('apellidos_acudiente', models.CharField(max_length=100, verbose_name='Apellidos del acudiente')),
                ('telefono_acudiente', models.CharField(max_length=10, validators=[applications.User.validators.validate_telefono], verbose_name='Teléfono del acudiente')),
                ('cedula_acudiente', models.CharField(max_length=20, validators=[applications.User.validators.validate_cero], verbose_name='Cédula del acudiente')),
                ('document', models.BooleanField(default=False)),
                ('simat', models.BooleanField(default=False)),
                ('siet', models.BooleanField(default=False)),
                ('actaBachillerato', models.BooleanField(default=False)),
                ('fotos', models.BooleanField(default=False)),
                ('serviciosPublicos', models.BooleanField(default=False)),
                ('carneSalud', models.BooleanField(default=False)),
                ('cedulaAcudiente', models.BooleanField(default=False)),
                ('certificados', models.BooleanField(default=False)),
                ('homologacion', models.BooleanField(default=False)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observacion')),
                ('is_active', models.BooleanField(default=True)),
                ('is_estudiante', models.BooleanField(default=True)),
                ('is_matriculado', models.BooleanField(default=False)),
                ('is_graduado', models.BooleanField(default=False)),
                ('masivo', models.BooleanField(default=False)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.programas')),
                ('periodo_matriculado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.periodos', verbose_name='Periodo')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.catalogssede', verbose_name='Sede')),
                ('tDocument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.catalogstypesdocuement', verbose_name='Tipo de documento')),
            ],
        ),
    ]
