# Generated by Django 4.0.5 on 2024-09-08 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0015_alter_banner_options_programas_tiene_grado'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_grado', models.CharField(max_length=15)),
                ('libro', models.PositiveIntegerField(verbose_name='Libro')),
                ('folio', models.PositiveIntegerField(verbose_name='Folio')),
                ('fecha_reg', models.DateField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.programas', verbose_name='Programa')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.estudiante', verbose_name='Estudiante')),
            ],
        ),
    ]
