# Generated by Django 4.0.5 on 2024-10-14 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_graduated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduated',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='graduated',
            name='periodo_grado',
        ),
        migrations.AlterField(
            model_name='graduated',
            name='fecha_reg',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
