# Generated by Django 4.2.8 on 2023-12-12 11:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teacher', '0001_initial'),
        ('User', '0005_catalogstypesactivities_alter_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200, verbose_name='Código de la asignatura')),
                ('nombre_materia', models.CharField(max_length=200, verbose_name='Nombre de la Asignatura')),
                ('an_creacion', models.CharField(default=datetime.datetime.now, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=15, unique=True)),
                ('an_creacion', models.CharField(default=datetime.datetime(2023, 12, 12, 12, 39, 31, 899426), max_length=50)),
            ],
            options={
                'ordering': ('-an_creacion',),
            },
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_prog', models.CharField(max_length=10, unique=True, verbose_name='Código del Programa')),
                ('programa_name', models.CharField(max_length=100, verbose_name='Nombre del Programa')),
                ('aceptado', models.PositiveIntegerField(verbose_name='Total materias para grado')),
                ('matricula', models.DecimalField(decimal_places=0, default=0, max_digits=25)),
                ('cuota_valor', models.DecimalField(decimal_places=0, default=0, max_digits=25)),
                ('cuotas', models.PositiveIntegerField(verbose_name='Numero de cuotas')),
                ('costo', models.DecimalField(decimal_places=0, default=0, max_digits=25)),
                ('an_creacion', models.CharField(default=datetime.datetime.now, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.catalogstypesprog')),
            ],
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_cierre', models.DateField()),
                ('cierre', models.DateField()),
                ('an_creacion', models.CharField(default=datetime.datetime.now, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.inventario')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.periodos')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.programas')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.catalogssede', verbose_name='Sede')),
            ],
            options={
                'ordering': ['materia'],
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.programas'),
        ),
    ]
