# Generated by Django 4.2.8 on 2023-12-13 01:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodos',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime(2023, 12, 13, 2, 39, 59, 624690), max_length=50),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='promedio')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Programs.materias', verbose_name='Materias')),
            ],
        ),
    ]
