# Generated by Django 4.2.8 on 2023-12-13 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_catalogstypesactivities_alter_user_created_at'),
        ('Student', '0001_initial'),
        ('Programs', '0002_alter_periodos_an_creacion_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.estudiante', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='banner',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.catalogstypesactivities', verbose_name='Tareas'),
        ),
    ]
