# Generated by Django 4.2.8 on 2023-12-19 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0003_banner_student_banner_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodos',
            name='an_creacion',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
