# Generated by Django 4.2.8 on 2023-12-27 19:49

import applications.User.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0004_alter_periodos_an_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias',
            name='programa',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='nombre_materia',
            field=models.CharField(max_length=200, validators=[applications.User.validators.validate_exist], verbose_name='Nombre de la Asignatura'),
        ),
        migrations.AlterField(
            model_name='programas',
            name='aceptado',
            field=models.PositiveIntegerField(validators=[applications.User.validators.validate_noncero], verbose_name='Total materias'),
        ),
        migrations.AlterField(
            model_name='programas',
            name='cuota_valor',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=25, validators=[applications.User.validators.validate_noncero], verbose_name='Valor de la mensualidad'),
        ),
        migrations.AlterField(
            model_name='programas',
            name='cuotas',
            field=models.PositiveIntegerField(validators=[applications.User.validators.validate_noncero], verbose_name='Número de cuotas'),
        ),
        migrations.AlterField(
            model_name='programas',
            name='matricula',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=25, validators=[applications.User.validators.validate_noncero], verbose_name='Valor de la matrícula'),
        ),
    ]
