# Generated by Django 4.2.8 on 2023-12-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0005_remove_materias_programa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='nombre_materia',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Asignatura'),
        ),
    ]
