# Generated by Django 4.2.8 on 2023-12-30 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_catalogsjornada_jornada'),
        ('Programs', '0006_alter_inventario_nombre_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='jornada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.catalogsjornada'),
            preserve_default=False,
        ),
    ]
