# Generated by Django 4.2.8 on 2024-01-03 23:58

import applications.User.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0008_alter_banner_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='programas',
            name='derechosGrado',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=35, validators=[applications.User.validators.validate_noncero], verbose_name='Valor de derechos a grado'),
        ),
    ]
