# Generated by Django 4.2.8 on 2024-01-15 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0009_programas_derechosgrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='an_creacion',
            field=models.CharField(default=datetime.datetime.now, max_length=50),
        ),
    ]
