# Generated by Django 4.2.8 on 2024-01-15 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0010_banner_an_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='an_creacion',
        ),
    ]
