# Generated by Django 4.2.8 on 2024-01-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0011_remove_banner_an_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='cod_tarea',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
