# Generated by Django 4.2.8 on 2024-01-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0013_banner_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='observacion',
            field=models.CharField(max_length=200),
        ),
    ]
