# Generated by Django 4.0.5 on 2024-09-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0014_alter_banner_observacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['cod_tarea']},
        ),
        migrations.AddField(
            model_name='programas',
            name='tiene_grado',
            field=models.BooleanField(default=False),
        ),
    ]
