# Generated by Django 4.0.5 on 2024-10-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programs', '0015_alter_banner_options_programas_tiene_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
